apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-4nyz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nphc-tenant/rhtap-demo-app/hacbs-test-project-4nyz@sha256:254706d4f9f1bd81793fa2b0289e3f8b7731f4e8079fd0801753485a5825bb82
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
